# Generated by Django 5.0.1 on 2024-05-02 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("professors_projects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="professor",
            name="department",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="project",
        ),
        migrations.AddField(
            model_name="professor",
            name="first_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="professor",
            name="last_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="professor",
            name="phone_number",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AddField(
            model_name="professor",
            name="professor_id",
            field=models.CharField(default="0000000000", max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name="project",
            name="claimed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="claimed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="professors_projects.student",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="first_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="last_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="phone_number",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AddField(
            model_name="student",
            name="student_id",
            field=models.CharField(default="0000000000", max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name="student",
            name="year_attended",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
