# Generated by Django 5.0.1 on 2024-05-25 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("professors_projects", "0003_project_is_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="max_students",
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name="project",
            name="project_id",
            field=models.CharField(default="1000", max_length=4, unique=True),
        ),
        migrations.RemoveField(
            model_name="project",
            name="claimed_by",
        ),
        migrations.CreateModel(
            name="ProjectClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="professors_projects.project",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="professors_projects.student",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="claimed_by",
            field=models.ManyToManyField(
                through="professors_projects.ProjectClaim",
                to="professors_projects.student",
            ),
        ),
    ]
