# Generated by Django 5.0.1 on 2024-05-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "professors_projects",
            "0004_project_max_students_project_project_id_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectclaim",
            old_name="student",
            new_name="students",
        ),
        migrations.AddField(
            model_name="project",
            name="project_file",
            field=models.FileField(blank=True, null=True, upload_to="project_files/"),
        ),
    ]
