# Generated by Django 5.0.1 on 2024-05-25 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("professors_projects", "0005_rename_student_projectclaim_students_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectclaim",
            name="students",
        ),
        migrations.CreateModel(
            name="ProjectClaimRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="professors_projects.project",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="professors_projects.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "student")},
            },
        ),
        migrations.AlterField(
            model_name="project",
            name="claimed_by",
            field=models.ManyToManyField(
                through="professors_projects.ProjectClaimRelation",
                to="professors_projects.student",
            ),
        ),
        migrations.AddField(
            model_name="projectclaim",
            name="students",
            field=models.ManyToManyField(to="professors_projects.student"),
        ),
    ]
