# Generated by Django 5.0.1 on 2024-05-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "professors_projects",
            "0006_remove_projectclaim_students_projectclaimrelation_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_id",
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
